### ISSUE TITLE
Port and instanceName are mutually exclusive, but only instanceName set

### ISSUE THREAD

**Issue by theweirdone** [chriseaton/rhino#4]
**Describe the bug**
Hi,
I'm trying to connect to a MSSQL database, but I keep getting the error that "Port and instanceName are mutually exclusive", but I've only set the instanceName in the config object. Port is not set.

**To Reproduce**
1. Create object:
```javascript
const config = {
    server: 'servername',
    options: {
        instanceName: 'instancename',
        readOnlyIntent: true,
        trustServerCertificate: true,
        encrypt: true,
        database: 'dbname',
        tdsVersion: '7_4',
    },
    authentication: {
        type: 'default',
        options: {
            userName: 'username',
            password: '********',
        },
    },
};
```
2. Run script

**Expected behavior**
I expect the connection to be made, but I get the error described. I'm assuming the default port is overriding my config options.

**Environment:**
 - OS & Version: macOS Catalina 10.15.7
 - Node Version: v14.13.0
 - Rhino Version: 5.3.2

**Relevant Logs/Stack Traces**
```
Error: Port and instanceName are mutually exclusive, but 1433 and instancename provided
    at new Connection (/Users/username/Code/playground/node_modules/tedious/lib/connection.js:552:15)
    at Connection.connect (/Users/username/Code/playground/node_modules/rhino/connection.js:302:35)
    at Rhino._createResource (/Users/username/Code/playground/node_modules/rhino/rhino.js:132:18)
    at /Users/username/Code/playground/node_modules/tarn/lib/Pool.js:389:34
    at Object.tryPromise (/Users/username/Code/playground/node_modules/tarn/lib/utils.js:53:24)
    at /Users/username/Code/playground/node_modules/tarn/lib/Pool.js:389:17
    at new Promise (<anonymous>)
    at callbackOrPromise (/Users/username/Code/playground/node_modules/tarn/lib/Pool.js:380:12)
    at Pool._create (/Users/username/Code/playground/node_modules/tarn/lib/Pool.js:290:9)
    at Pool._doCreate (/Users/username/Code/playground/node_modules/tarn/lib/Pool.js:260:36)
```

**Comment by chriseaton** [comment]
Thanks for reporting this. Will have a fix out shortly.

**Comment by chriseaton** [comment]
v5.3.3 has been published with the fix.
