### ISSUE TITLE
Database Connection Reset During a Query Crashes the Script

### ISSUE THREAD

**Issue by LegendaryMediaTV** [chriseaton/rhino#5]
**Describe the bug**
If the query connection resets during a `query` call, the script crashes. The stack trace points to Tedious, but I wasn't sure if Rhino can pass along the error instead of being uncatchable.

**To Reproduce**
1. connect to an MSSQL database via Rhino
2. execute an `await db.query(sql)` command within a `try`/`catch`
3. if the query connection resets along the way, then the script crashes

**Expected behavior**
If the database connection is reset during a `query`, the error should be catchable instead of crashing the script.

**Environment:**
 - OS & Version: Windows 10 12H2
 - Node Version: v14.18.1
 - Rhino Version: 5.4.0

**Relevant Logs/Stack Traces**
```
events.js:377
      throw er; // Unhandled 'error' event
      ^

ConnectionError: Connection lost - read ECONNRESET
    at Connection.socketError (C:\Users\sample\project\node_modules\tedious\lib\connection.js:1377:26)
    at Socket.<anonymous> (C:\Users\sample\project\node_modules\tedious\lib\connection.js:1138:14)
    at Socket.emit (events.js:412:35)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on Connection instance at:
    at Connection.emit (C:\Users\sample\project\node_modules\tedious\lib\connection.js:1027:18)
    at Connection.socketError (C:\Users\sample\project\node_modules\tedious\lib\connection.js:1377:12)
    at Socket.<anonymous> (C:\Users\sample\project\node_modules\tedious\lib\connection.js:1138:14)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ESOCKET',
  isTransient: undefined
}
```

**Comment by chriseaton** [comment]
Hmm should be trappable. My guess is it's bypassing the event bubbler tedious uses. Will work on it.
